package com.sysco.product;


public class ProductTestData {
    public static final String SUPC = "2582005";
    public static final String IMAGE_URL = "./" + SUPC + "/web/1.jpg";
    public static final String NAME = "SOUP CREAM OF POTATO CONC";
    public static final String DESCRIPTION = "Soup Cream Of Potato Concentrate";
    public static final String AVG_WEIGHT_PER_CASE = "12.0";
    public static final String STORAGE_LOCATION = "F";
    public static final String SPLIT_CODE="N";
    public static final String THREE_EACH_PER_PACK = "3";
    public static final String PACK_SIZE_FOUR_LBS = "4 LB";
    public static final String CASE_OR_EACH = "CS or EA";
    public static final String EXTERNAL_UPC="10074865355565";
    public static final String CORE_INDICATOR=null;
    public static final String STOCK_INDICATOR="S";
    public static final String STOCK_STATUS="Warehouse";
    public static final String MANUFACTURER_CODE="35556";
    public static final String COMPLETE_CATEGORY_ID = "002055010";
    public static final int MAIN_CATEGORY_ID = 6 ;
    public static final String LABEL = "CONCENTRATE";
    public static final String THIRD_LINE_DESCRIPTION = "LARGE DICES OF POTATO WITH CARROTS CELERY AND ONIONS BLENDED WITH FRESH CREAM FOR UNMATCHED " +
            "FLAVOR AND VELVETY MOUTH FEEL. BALANCED FLAVOR AND RELIABLE CONSISTENCY MAKE THIS SOUP AN IDEAL BASE FOR SIGNATURE CLAM CHOWDER AND " +
            "LOADEDPOTATO SOUPS. - - PRODUCT BENEFITS: SALES SOUP CAN BOOST CHECK AVERAGES BY UP TO FIFTEEN PERCENT. CONSISTENCY SAME HIGHQUALITY " +
            "AND DELICIOUS TASTE IN EVERY SERVING. VARIETY SUPPLEMENT SCRATCH OFFERINGS WITH DIVERSE FROZEN FLAVORS. -- COMPARABLE PRODUCTS: N/A - - " +
            "PACKING INFORMATION: SPLIT TRAY PACK MAKES IT EASY TO PREPARE AS LITTLE AS HALF GALLON OF SOUP. EACH TRAYIS LABELED WITH INGREDIENT " +
            "NUTRITION AND HEATINGINFORMATION. -- PREP & COOKINGINSTRUCTIONS: PREPARATION REMOVE PLASTIC FILM COVER. PLACE BLOCKS OFSOUP IN A SUITABLE " +
            "CONTAINER.ADD ONE QUART OF WATER FOR EACH BLOCK OF SOUP. ONEHALF OF THE TRAY FILLED TO THE TOP OF THE CENTERDIVIDER IS ONE QUART. COVER " +
            "AND HEAT TO BOILING WITH OCCASIONAL STIRRING. USE INDIRECT HEAT EX DOUBLE BOILER FOR OPTIMALQUALITY. REDUCE HEAT AND SIMMER FOR TWO TO THREEMINUTES." +
            " TRANSFER TO SERVING CONTAINER CAREFULLY.HANDLING GUIDELINES DO NOT USEIF PUNCTURED OR TORN. KEEP FROZEN UNTIL READY TOUSE. DO NOT REFREEZE. " +
            "PROMPTLY REFRIGERATE UNUSEDCOOKED SOUP IN SEPARATE CONTAINER.";
    //TODO: Remove when item_service gets full thirdlineDescription
    public static final String THIRD_LINE_DESCRIPTION_SVC = "LARGE DICES OF POTATO WITH CAR";

}
