package com.sysco.model;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class NutritionResponse {
    private String calories;
    private String caloriesUOM;
    private String totalFat;
    private String totalFatUOM;
    private String totalFatDailyValue;
    private String saturatedFat;
    private String saturatedFatDailyValue;
    private String saturatedFatUOM;
    private String transFat;
    private String transFatUOM;
    private String cholesterol;
    private String cholesterolUOM;
    private String cholesterolDailyValue;
    private String sodium;
    private String sodiumUOM;
    private String sodiumDailyValue;
    private String totalCarbohydrate;
    private String totalCarbohydrateUOM;
    private String totalCarbohydrateDailyValue;
    private String dietaryFiber;
    private String dietaryFiberUOM;
    private String dietaryFiberDailyValue;
    private String sugars;
    private String sugarsUOM;
    private String protein;
    private String proteinUOM;
    private String ingredients;
    private String servingSize;
    private String allergens;
    private String mayAllergens;
    private String cnIdentification;
    private String calcium;
    private String calciumUOM;
    private String calciumDailyValue;
    private String childNutrition;
    private String glutenFree;
    private String grade;
    private String green;
    private String typeOfGreen;
    private String halalCertified;
    private String iron;
    private String ironUOM;
    private String ironDailyValue;
    private String typeOfKosher;
    private String notes;
    private String organic;
    private String typeOfOrganic;
    private String potassium;
    private String potassiumUOM;
    private String potassiumDailyValue;
    private String productBenefits;
    private String productFormulationStatement;
    private String fruit;
    private String grainBread;
    private String vegetableBeansPeas;
    private String vegetableDarkGreen;
    private String vegetableOther;
    private String vegetableRedOrange;
    private String vegetableStarchy;
    private String meat;
    private String portionSize;
    private String vegetarian;
    private String typeOfVegetarian;
    private String vegan;
    private String kosherCertified;
    private String vitaminC;
    private String vitaminCUOM;
    private String vitaminCDailyValue;
    private String servingSizeWeight;
    private String vitaminA;
    private String vitaminAUOM;
    private String vitaminADailyValue;
    private String vitaminD;
    private String vitaminDUOM;
    private String vitaminDDailyValue;
}
